// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMAWP5heH6spuMqY5dV1duNiCDSJfxfEc',
    appId: '1:374913205578:web:5d54f5f19666a8bc07adb3',
    messagingSenderId: '374913205578',
    projectId: 'thriftify-app',
    authDomain: 'thriftify-app.firebaseapp.com',
    storageBucket: 'thriftify-app.appspot.com',
    measurementId: 'G-K765N7WQ7E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyN_2y6DvuxetvQoUCobr6kT7AbWXGgTM',
    appId: '1:374913205578:android:bbd934a7c196f6d707adb3',
    messagingSenderId: '374913205578',
    projectId: 'thriftify-app',
    storageBucket: 'thriftify-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3IRGZWacLGJ8V2Wq1HX2weCqBlbK2vGA',
    appId: '1:374913205578:ios:eeba79ab11d9703607adb3',
    messagingSenderId: '374913205578',
    projectId: 'thriftify-app',
    storageBucket: 'thriftify-app.appspot.com',
    iosClientId: '374913205578-astqtlgludpg3ogv8b7gpd0gc8dlp8ij.apps.googleusercontent.com',
    iosBundleId: 'com.gdsctknp.suproVigilant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3IRGZWacLGJ8V2Wq1HX2weCqBlbK2vGA',
    appId: '1:374913205578:ios:eeba79ab11d9703607adb3',
    messagingSenderId: '374913205578',
    projectId: 'thriftify-app',
    storageBucket: 'thriftify-app.appspot.com',
    iosClientId: '374913205578-astqtlgludpg3ogv8b7gpd0gc8dlp8ij.apps.googleusercontent.com',
    iosBundleId: 'com.gdsctknp.suproVigilant',
  );
}
