// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ4Fq-GTc59Du_kIZdAePbURSN2Wjkhqk',
    appId: '1:1046716731026:web:cfe9c4ff2fabb255b1604b',
    messagingSenderId: '1046716731026',
    projectId: 'supro-vigilant',
    authDomain: 'supro-vigilant.firebaseapp.com',
    storageBucket: 'supro-vigilant.appspot.com',
    measurementId: 'G-LZNFPDDEY1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGt29en4Lsr9qDX-HlNWt5NQG-6Ekwujg',
    appId: '1:1046716731026:android:c537f4e3f8bca775b1604b',
    messagingSenderId: '1046716731026',
    projectId: 'supro-vigilant',
    storageBucket: 'supro-vigilant.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWNz0GfHPmV27w_wY14kR7nPjWsUv3WEw',
    appId: '1:1046716731026:ios:cb2549be91b501e8b1604b',
    messagingSenderId: '1046716731026',
    projectId: 'supro-vigilant',
    storageBucket: 'supro-vigilant.appspot.com',
    iosClientId: '1046716731026-5qdaglpsh5bq32sfihh2ncur3ql84crj.apps.googleusercontent.com',
    iosBundleId: 'com.gdsctknp.suproVigilant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWNz0GfHPmV27w_wY14kR7nPjWsUv3WEw',
    appId: '1:1046716731026:ios:cb2549be91b501e8b1604b',
    messagingSenderId: '1046716731026',
    projectId: 'supro-vigilant',
    storageBucket: 'supro-vigilant.appspot.com',
    iosClientId: '1046716731026-5qdaglpsh5bq32sfihh2ncur3ql84crj.apps.googleusercontent.com',
    iosBundleId: 'com.gdsctknp.suproVigilant',
  );
}
